CREATE TABLE roles_setting (
    id INT PRIMARY KEY AUTO_INCREMENT,
    role_id INT,
    user_id INT,
    active_status VARCHAR(1) NOT NULL
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);